### ISSUE TITLE
Analyzer proposal: pass CancellationToken explicitly

### ISSUE THREAD

**Issue by sharwell** [microsoft/vs-threading#591] opened 2020-02-14 16:29 UTC
This analyzer would report cases where a method is called with an implicit cancellation token:

```csharp
async Task Method1Async() {
  await Method2(); // Diagnostic
  await Method3(); // Diagnostic
  Method4(); // Diagnostic
}

async Task Method2Async(CancellationToken cancellationToken = default) { }

async Task Method3Async() { }
async Task Method3Async(CancellationToken cancellationToken) { }

void Method4() { }
void Method4(CancellationToken cancellationToken) { }
```

Each of the three cases [should|should not] have the same diagnostic ID:

1. Calling an asynchronous method using the default value for an optional `CancellationToken` parameter
2. Calling an overload of an asynchronous method, where a different overload accepts a `CancellationToken`
3. Calling a synchronous method that accepts a `CancellationToken` (as an optional parameter or a different overload)

**Comment by AArnott** [comment] 2020-02-14 16:31
See also #394 and consider how they will relate.

**Comment by gundermanc** [comment] 2020-03-17 20:33
+1 on this one. See this recent regression bug in LSP client due to failure to propagate CancellationTokens: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1083283

It has actually been fixed on at least 2 occasions before.

**Comment by Youssef1313** [comment] 2020-08-26 14:39
This was implemented in roslyn-analyzers in https://github.com/dotnet/roslyn-analyzers/pull/3641

**Closed** 2020-08-26 15:00 UTC
Labels: analyzers
