### ISSUE TITLE
VSTHRD002 should not warn after testing for task completion.

### ISSUE THREAD

**Issue by NN---** [microsoft/vs-threading#698] opened 2020-10-20 08:54 UTC
#### Bug description

VSTHRD002 should not warn after testing for task completion.

#### Repro steps

```cs
int g(ValueTask<int> t)
{
  // VSTHRD002
  if (t.IsCompleted) return t.Result;

  // VSTHRD002
  if (t.IsCompletedSuccesfuly) return t.Result;

  return 1;
}
```

#### Expected behavior
No warning.

#### Actual behavior
Warning VSTHRD002

- Version used: 16.7.56
- Application (if applicable):

**Comment by AArnott** [comment] 2020-10-20 16:40
Duplicate of #301

**Closed by AArnott** 2020-10-20 16:41 UTC
