### ISSUE TITLE
VSTHRD100 does not recognize event handlers

### ISSUE THREAD

**Issue by dieterv** [microsoft/vs-threading#547] opened 2019-10-30 20:30 UTC
I'm working on a winforms project and had VSTHRD100 mark some `async void` signatures in my code. I referred to [Async/Await - Best Practices in Asynchronous Programming](https://msdn.microsoft.com/en-us/magazine/jj991977.aspx) for more information and it seems event handlers are an exception to this rule.

Is it possible for VSTHRD100 to not flag `async void` event handlers?

**Comment by sharwell** [comment] 2019-10-30 20:31
Duplicate of #447

**Closed** 2019-10-30 20:52 UTC
