### ISSUE TITLE
Memory leak from VS Threading analyzers from DiagnosticAnalyzerBase.customAwaitableTypes 

### ISSUE THREAD

**Issue by mavasani** [microsoft/vs-threading#508] opened 2019-09-01 14:54 UTC
#### Bug description
While investigating memory leak from https://github.com/dotnet/roslyn/issues/38330, I found out that the VS Threading analyzers package has a concurrent dictionary keyed on `ITypeSymbol` as a private field for all its analyzers, which is causing it to hold onto the symbols/compilation and this leads to Solution instances to leak and continuous increasing memory usage:
https://github.com/microsoft/vs-threading/blob/27533323247ff1ee1a5c43c7cd91302d7eb9536d/src/Microsoft.VisualStudio.Threading.Analyzers/DiagnosticAnalyzerBase.cs#L28

```

Name | Inc % | Inc
-- | -- | --
+ [.NET Roots] | 100.0 | 296,243,104
+ [static vars] | 95.7 | 283,643,616
\|+ [static var Microsoft.CodeAnalysis.Remote.SolutionService.s_primarySolution] | 64.9 | 192,211,600
\|\|+ mscorlib!Tuple | 64.9 | 192,211,600
\|\| + Microsoft.CodeAnalysis.Workspaces!Microsoft.CodeAnalysis.Solution | 64.9 | 192,210,544
\|\|  + Microsoft.CodeAnalysis.Workspaces!Microsoft.CodeAnalysis.SolutionState | 64.8 | 191,892,624
\|\|  \|+ System.Collections.Immutable!Immutable.ImmutableDictionary | 48.2 | 142,861,984
\|\|  \|\|+ System.Collections.Immutable!Immutable.SortedInt32KeyNode> | 48.2 | 142,861,936
\|\|  \|\| + Microsoft.CodeAnalysis.Workspaces!Microsoft.CodeAnalysis.ProjectState | 48.2 | 142,860,032
\|\|  \|\|  + Microsoft.CodeAnalysis.Workspaces!Microsoft.CodeAnalysis.ProjectInfo | 47.1 | 139,609,392
\|\|  \|\|  \|+ System.Collections.Immutable!Immutable.ImmutableArray | 46.4 | 137,354,384
\|\|  \|\|  \|\|+ Microsoft.CodeAnalysis!Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference | 46.4 | 137,352,848
\|\|  \|\|  \|\| + Microsoft.CodeAnalysis!Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference+Extensions | 46.4 | 137,342,016
\|\|  \|\|  \|\| \|+ System.Collections.Immutable!Immutable.ImmutableDictionary> | 46.4 | 137,323,984
\|\|  \|\|  \|\| \|\|+ System.Collections.Immutable!Immutable.SortedInt32KeyNode>> | 46.4 | 137,323,632
\|\|  \|\|  \|\| \|\| + Microsoft.VisualStudio.Threading.Analyzers!Microsoft.VisualStudio.Threading.Analyzers.VSTHRD200UseAsyncNamingConventionAnalyzer | 46.3 | 137,280,080
\|\|  \|\|  \|\| \|\|  + mscorlib!ConcurrentDictionary | 46.3 | 137,280,064
\|\|  \|\|  \|\| \|\|   + mscorlib!ConcurrentDictionary+Tables | 46.3 | 137,279,984
\|\|  \|\|  \|\| \|\|    + mscorlib!ConcurrentDictionary+Node | 46.3 | 137,275,040

```

#### Repro steps
I can share a gcdump file showing the above leak if required. I also have custom repro steps (with some local workarounds) to repro this consistently - I can buddy test any fix or provide you the repro steps if required.

#### Expected behavior
No memory leak

#### Actual behavior
Memory leak in ServiceHub.RoslynCodeAnalysisService process

- Version used: Latest 16.3 dogfood builds and VS Threading analyzers NuGet package

#### Additional context
It is strongly recommended that analyzers do not hold onto strong references to any symbols or compilation. Easiest fix here is to switch the dictionary to `ConcurrentDictionary<string, bool> customAwaitableTypes`, by using the fully qualified name of the type as the key instead of the symbol.

**Comment by AArnott** [comment] 2019-09-01 18:26
Thanks for reporting, @mavasani. I'm confused by the analyzer's lifecycle. I've heard conflicted reports on this. Where is the documentation for when analyzers are instantiated and released?

**Comment by mavasani** [comment] 2019-09-02 01:35
Tagging @heejaechang. I believe originally the analyzers from NuGet packages were never used past a single compilation, but this seems to be no longer true in IDE analysis. Heejae are we using the analyzer instances across compilations? I believe that is also the likely cause of the performance regression in FxCop analyzers package noted in https://github.com/dotnet/roslyn/issues/38330. Note that the analyzer action semantics laid out originally by John Hamby did not restrict re-use of analyzer instances across compilations: https://github.com/dotnet/roslyn/blob/master/docs/analyzers/Analyzer%20Actions%20Semantics.md. So theoretically, it is best to make no assumptions about analyzer's lifetime.

**Comment by AArnott** [comment] 2019-09-02 02:57
Thanks. I used to assume that and not store anything in fields of analyzer classes, and instead let it all be stored in closures for individual registrations. But someone since then (@sharwell, perhaps) advised me that analyzers don't live beyond one compilation so I shifted to use fields, which was simpler.

I believe the lifecycle should be very clearly defined. I can't see a defined behavior in the doc you linked to. Can we please get it documented? And IMO it would be best/simplest if analyzers were created for each compilation so that we could use fields safely.
I can certainly imagine a simple fix for this particular issue on the threading analyzers side, but if this is a regression due a change in roslyn behavior for how analyzers are retained in memory, perhaps that should be reverted and documented going forward.

**Comment by sharwell** [comment] 2019-09-02 03:32
The semantics I understood is you can create a Compilation Start callback, and within that callback create an instance which will hold state for the compilation. That instance will not be reused across compilations because the next compilation will call Compilation Start again. State can be stored in fields only when those fields are members of the instance created by a Compilation Start callback (or in 3.0+, a Symbol Start callback).

**Comment by mavasani** [comment] 2019-09-02 03:51
@sharwell is correct. You can use the [TryGetValue](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs,584) API on the compilation start analysis context to store compilation wide state per syntax tree or source text, without recomputation cost. However, if the underlying [value provider](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/SyntaxTreeValueProvider.cs,11) outlives the compilation, then it's underlying [CWT](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalysisValueProvider.cs,14) storing the state may prevent GC. So either the provided value provider should not outlive the compilation OR should not hold onto any symbol/compilation data.

@heejaechang Is it possible for the IDE analysis to not re-use analyzer instances from project's AnalyzerReferences (not the host ones from VSIXes) across different compilations?

**Comment by sharwell** [comment] 2019-09-02 04:06
> Is it possible for the IDE analysis to not re-use analyzer instances from project's AnalyzerReferences (not the host ones from VSIXes) across different compilations?

StyleCop Analyzers is relatively heavily optimized for cases where the instances are reused.

**Comment by AArnott** [comment] 2019-09-02 12:44
Very well, I'll make adjustment here. Thanks.

**Closed** 2019-09-04 14:03 UTC
Labels: analyzers, bug
