### ISSUE TITLE
VSTHRD110 mis-fires on null coalescing operator

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-threading#881] opened 2021-07-26 20:59 UTC
#### Bug description

When an async method's result is returned with `??` operator, VSTHRD110 claims the result isn't returned or awaited.

#### Repro steps

```cs
        internal Task<T> GetClientAsync<T>(CancellationToken cancellationToken) where T : VssHttpClientBase
        {
            return _vssConnection?.GetClientAsync<T>(cancellationToken) ?? Task.FromResult<T>(null);
        }
```

#### Expected behavior
 
No warning.

#### Actual behavior

A warning.

**Comment by drewnoakes** [comment] 2021-08-01 12:57
Duplicate of #880?

**Comment by AArnott** [comment] 2021-08-17 17:14
The two issues are regarding distinct analyzers. I wouldn't know till fixing it whether there is common code behind each analyzer such that fixing one will implicitly fix the other.

**Comment by peterdrier** [comment] 2023-06-15 10:35
`private Task ShakeTreeAsync() => Tree?.ShakeAsync() ?? Task.CompletedTask;`

A simple example causing a VSTHRD110 warning where it shouldn't.

**Closed** 2023-10-25 18:10 UTC
Labels: bug, analyzers
