### ISSUE TITLE
VSTHRD100 Avoid async void methods - false positive if event handler

### ISSUE THREAD

**Issue by DrGriff** [microsoft/vs-threading#510] opened 2019-09-02 10:33 UTC
#### Bug description
Getting a compile error for an asynchronous event handler.  In this case, async void is acceptable

#### Repro steps
Add an async event handler which returns async task.

#### Expected behavior
Not to warn about event handlers

#### Actual behavior
Gives warning

- Version used: Visual Studio 2019
- Application (if applicable): 

#### Additional context
Not clear how I can suppress this error

**Comment by weltkante** [comment] 2019-09-02 11:25
>  In this case, async void is acceptable

I disagree, `async void` is a problem because uncaught exceptions will tear down the process by default, we disallow them on events as well (but provide our own utility methods in case the event wants to kick off something async).

> Not clear how I can suppress this error

adding a `[SuppressMessage("", "VSTHRD100")]` attribute to the event handler is probably the cleanest solution

**Comment by AArnott** [comment] 2019-09-02 13:04
> But be warned that if you fail to catch all exceptions the GC will kill the process by default.

Just a nit, but the GC doesn't kill the process. What happens is the C# compiler's async void wrapper will rethrow the exception on `SynchronizationContext.Current`. Most sync contexts are implemented to crash when any delegate they invoke throws an unhandled exception. And if you have no sync context, it is thrown on the threadpool, which always crashes the process as well.

**Comment by AArnott** [comment] 2019-09-02 13:04
Duplicate of #447

**Closed by AArnott** 2019-09-02 13:04 UTC
