### ISSUE TITLE
Code fix for VSTHRD103 throws an exception

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#169] opened 2017-07-28 17:43 UTC
Code sample:

```csharp
async Task MethodAsync(IServiceProvider serviceProvider)
{
  var dte = serviceProvider.GetService<SVsSolution, IVsSolution>();
}
```

When VSTHRD103 was reported, the code fix crashed because `IServiceProvider` does not define `GetServiceAsync`.

Stack trace:

```
System.AggregateException : One or more errors occurred. ---> Value cannot be null.
Parameter name: syntax
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
---> (Inner Exception #0) System.ArgumentNullException : Value cannot be null.
Parameter name: syntax
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckModelAndSyntaxNodeToSpeculate(CSharpSyntaxNode syntax)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.TryGetSpeculativeSemanticModelForMethodBody(Int32 position,BaseMethodDeclarationSyntax method,SemanticModel& speculativeModel)
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.TryGetSpeculativeSemanticModelForMethodBody(SemanticModel semanticModel,Int32 position,BaseMethodDeclarationSyntax method,SemanticModel& speculativeModel)
   at async Microsoft.VisualStudio.Threading.Analyzers.VSTHRD103UseAsyncOptionCodeFix.ReplaceSyncMethodCallWithAwaitAsync.GetChangedDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionInternalAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetChangedDocumentsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetDocumentIdToChangedDocuments(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.TryMergeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.TryGetMergedFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.GetFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsAsync(<Unknown Parameters>)<---
```

**Comment by AArnott** [comment] 2017-07-28 18:31
@sharwell which `IServiceProvider` type are you using in your code sample here? It's not `System.IServiceProvider`.

**Comment by sharwell** [comment] 2017-07-28 18:43
Ah, it is `System.IServiceProvider`, but I simplified it too much. The original code calls `GetDTE`, where the following two extension methods exist:

```csharp
public static EnvDTE.DTE GetDTE(this IServiceProvider serviceProvider)
{
    return serviceProvider.GetService<SDTE, EnvDTE.DTE>();
}

public static Task<EnvDTE.DTE> GetDTEAsync(
    this Microsoft.VisualStudio.Shell.IAsyncServiceProvider site)
{
    return site.GetServiceAsync<SDTE, EnvDTE.DTE>();
}
```

**Comment by AArnott** [comment] 2017-07-28 18:52
Even with those two methods, I don't see any definition for `IServiceProvider.GetService<S, I>()` which your original sample invoked. And I can't (yet) fathom why the analyzer would misfire on your sample asking you to invoke `GetServiceAsync` when no such method exists.

Can you perhaps update the original sample with everything required (using statements, mentions of assembly references) to compile the snippet? This will help me understand what's going wrong and also write a unit test for it.

**Comment by sharwell** [comment] 2017-07-28 18:53
Here's the full extension methods class:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.VisualStudio.Common/ServiceProviderExtensions.cs

**Comment by AArnott** [comment] 2017-07-28 18:58
OK, so if I'm reading the code in your links correctly, the original sample is wrong because you say it calls `GetService` but it actually calls `GetDTE`. And the code fix wants to switch from `GetDTE` (on `IServiceProvider`) to `GetDTEAsync` (on `IAsyncServiceProvider`) even though we don't have an `IAsyncServiceProvider`. Is that right?

**Comment by sharwell** [comment] 2017-07-28 19:02
Yes, I tried to simplify the example, but in reality I broke it.

**Comment by AArnott** [comment] 2017-07-29 18:24
I'm not having any luck reproducing this in isolation based on what you've given me. I'll try enlisting in the nuget repo myself to repro, but previous attempt to get nuget.client to build for me have failed, so I'm not optimistic.

**Comment by AArnott** [comment] 2017-07-29 19:05
I don't yet know why any diagnostic is reported here at all, but the exception isn't because `GetServiceAsync` doesn't exist. I think it's because the fix would be applied at a location where there is no parent `MethodDeclarationSyntax` (because it's within an anonymous method within a constructor).

**Comment by AArnott** [comment] 2017-07-29 20:50
It looks like at least one, if not both, of the underlying causes of this failure are already fixed in the latest release. I see NuGet is using 15.0.240 but 15.3.35 is already out with the fixes. Please verify and let me know if we should re-open.

**Closed by AArnott** 2017-07-29 20:50 UTC
Labels: analyzers, bug
