### ISSUE TITLE
Unwanted analyzers are passed to dependent projects

### ISSUE THREAD

**Issue by kinetiq** [microsoft/vs-threading#1165] opened 2023-03-13 23:35 UTC
#### Bug description
In a library I'm workng on, I want to use the Microsoft.VisualStudio.Threading for async events. However, this package depends on Microsoft.VisualStudio.Threading.Analyzers

The analyzers are great, however I do not want people who consume my library to have these forced on them, and then possibly choose not to use my library as a result.

More details and some ideas that didn't work: https://stackoverflow.com/questions/75701868/how-can-i-reference-a-nuget-package-that-contains-a-dependency-on-static-code-an/75707858#75707858

IMO, the analyzers dependency should not be packaged with Microsoft.VisualStudio.Threading at all for this reason. I should be able to choose one or both.

Thanks for the great work!

**Comment by AArnott** [comment] 2023-03-14 14:56
You have my full support on wanting this.

This is a duplicate of #605, and ultimately tracked by https://github.com/microsoft/vs-streamjsonrpc/issues/195.

**Closed by AArnott** 2023-03-14 14:56 UTC
