### ISSUE TITLE
VSTHRD110 ("Observe the awaitable result of this method call by awaiting it, assigning to a variable, or passing it to another method.") fires when being conditionally returned

### ISSUE THREAD

**Issue by dpugh** [microsoft/vs-threading#899] opened 2021-08-27 17:13 UTC
#### Bug description
This line of code:
            await Task.WhenAll(composedCommands.Select(command => command.Value?.InitializeAsync(this, cancellationToken) ?? Task.CompletedTask));
Generates the VSTHRD110 error (on "InitializeAsync") even though the result is being returned.

Modifying the code to:
            await Task.WhenAll(composedCommands.Select(command => command.Value.InitializeAsync(this, cancellationToken)));
Removes the error,

#### Repro steps
See above.

#### Expected behavior
I wouldn't expect the error to be generated on the original code since it is not ignoring/discarding the result.

- Version used: 
Noticed the issue after updating a VSIX to use VS dlls 17.0.0-previews-4-31620-382

**Comment by drewnoakes** [comment] 2021-08-31 09:35
Seems like a dupe of #880 and/or #881.

**Comment by AArnott** [comment] 2021-08-31 14:29
Maybe so. The syntax is slightly different than #881, and #880 is for a different analyzer, so I'll keep them all active. Maybe we'll get lucky and can close them all with one fix though.

**Comment by AArnott** [comment] 2023-01-19 19:33
Another syntax that fails is `return task?.ContinueWith();` from a `Task?` returning method.

**Comment by jeanplevesque** [comment] 2023-10-16 14:05
I think I'm having this problem too but with `IObservable<T>`.
![image](https://github.com/microsoft/vs-threading/assets/39710855/56cb7234-e620-4be0-8e57-ae7368dc164a)

**Comment by AArnott** [comment] 2023-10-24 19:34
Duplicate of #881

**Closed by AArnott** 2023-10-24 19:34 UTC
Labels: bug, analyzers
