### ISSUE TITLE
VSTHRD110 reporting incorrectly on expressions using null-coalescing operator

### ISSUE THREAD

**Issue by drewnoakes** [microsoft/vs-threading#880] opened 2021-07-23 23:16 UTC
In https://github.com/dotnet/project-system/pull/7424 we updated `Microsoft.VisualStudio.Threading.Analyzers` from 17.0.21-alpha to 17.0.26-alpha. This introduced two new VSTHRD110 diagnostics (Observe result of async calls), both of which look invalid.

The expressions in question:

```c#
return _control?.ApplyAsync() ?? Task.FromResult((int)HResult.Fail);
```

```c#
return _solutionService?.LoadedInHost.WithCancellation(_tasksService.UnloadCancellationToken) ?? throw new NotSupportedException();
```

These look very similar in structure, suggesting a pattern that the analyzer doesn't handle correctly.

**Comment by AArnott** [comment] 2023-10-24 19:33
I corrected the bug title and description since the wrong analyzer ID was used. As such, this is now a duplicate of #899.

**Closed by AArnott** 2023-10-24 19:33 UTC
Labels: bug, analyzers
