### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/vs-threading#473] opened 2019-03-22 06:33 UTC
#### Bug description
Having watched David Fowler & Damien Edwards video (https://www.youtube.com/watch?v=-cJjnVTJ5og), I added this library into my application so I can use JoinableTaskFactory and the analyzers.

I have hit a memory leak in my application when I use the JoinableTaskFactory.  This memory leak only occurs in the context of Asp.Net and does **not occur in a console application**.  So I am not 100% sure where the bug lies, or even if there is a bug.

The issue occurs when I am doing SyncOverAsync with JoinableTaskFactory.  If I just call **.Result** instead, the memory leak does not occur.

I have used Ants Memory Profiler to try and see what is going on and it looks like the MemoryStreams are kept in memory by the JoinableTaskFactory.

Here is the Ants Memory Profiler results: 
[jtf-profiler.zip](https://github.com/Microsoft/vs-threading/files/2995278/jtf-profiler.zip)

Here are some screenshots from Ants:

![image](https://user-images.githubusercontent.com/102243/54805129-1327f000-4cca-11e9-9052-59fe62d88355.png)

![image](https://user-images.githubusercontent.com/102243/54805154-2d61ce00-4cca-11e9-95ab-deaa697cf5a9.png)

#### Repro steps
I have created a solution to repro the issue.

https://github.com/gregpakes/JTF-Memory-AspNet

#### Expected behavior
I would expect that the when using the JoinableTaskFactory, the memory usage should be somewhat similar to not using it.

#### Actual behavior
The memory usage grows until either the process stops or an out of memory exception occurs.

**Comment by AArnott** [comment] 2019-03-23 03:25
Thanks for the fantastic bug report!

This appears to be a dupe of #274
If you upgrade to the 16.0 version, I think you'll see the leak go away. 

That said, I think you may have a leak anyway. The fix from 16.0 will drop the size of the leak significantly, but it appears you may have set up a Task continuation chain where Tasks don't get GC'd. 

Taking a quick look at your repro solution, I see you're creating a new `JoinableTaskContext` every time you're synchronously blocking. That is *not* how it's designed to be used. The design is to create that object just one per thread that has a single-threaded `SynchronizationContext`. I'm not sure how well that translates into an ASP.NET context, and _maybe_ it doesn't matter. 

I don't see where you're never-releasing task chain is coming from. Can you upgrade to 16.0 and see if there is any leak left? Maybe it's still there but much smaller. And maybe it's there in the non-JoinableTaskFactory path as well, I don't know.

**Comment by gregpakes** [comment] 2019-03-23 04:13
Thanks for the response.

There is a reason we are not using 16.0. From memory it adds a dependency that didn’t work in our solution, but I will revisit that.

Thanks for the feedback regarding the JoinableTaskContext. In all honesty, I don’t fully understand the library and used it because various analysers said I should!!! 

Maybe I should go away and investigate how to use it properly!  I haven’t seen any guidance on how to use it properly can you point me to it?

I’ll try upgrading to 16.x in the repro solution and see if it hangs around.

**Comment by AArnott** [comment] 2019-03-23 04:21
Great, yes the docs are mostly all on this site. But they mostly deal with client apps, so I'm interested in hearing back from you on your ASP.NET uses. Most of the analyzers should apply to ASP.NET, but some may not. ASP.NET apps should avoid blocking threads using Task.Wait or JoinableTaskFactory.Run whenever possible to avoid hurting the scalability of your site.

**Comment by gregpakes** [comment] 2019-03-23 04:38
I can confirm that upgrading to 16.x does resolve the leak.  I will go and refresh my memory why we couldn't use it.. I think it's something to do with these dependencies:

- Microsoft.VisualStudio.Validation
- System.Threading.Tasks.Extensions

So I'm now thinking I need to provide a helper class in the application to allow everyone to go and get the single JoinableTaskContext.  I'm assuming I'm understanding that correctly.

**Comment by AArnott** [comment] 2019-03-23 14:51
`Microsoft.VisualStudio.Validation` is not a new dependency. `System.Threading.Tasks.Extensions` probably is, and IIRC was necessary for our support of `ValueTask`.

> So I'm now thinking I need to provide a helper class in the application to allow everyone to go and get the single JoinableTaskContext. 

Yes, that's what I'd recommend. For ASP.NET since there is no main thread, you should probably instantiate the `JoinableTaskContext` after being sure to clear the `SynchronizationContext.Current` value so it understands there is no main thread. You also don't need to new up your own `JoinableTaskFactory1 since the `JoinableTaskContext` has a default factory exposed as a property.

**Closed by AArnott** 2019-03-23 14:51 UTC

**Comment by gregpakes** [comment] 2019-03-23 16:58
Would you recommend that I give up trying to use this in Asp.Net and come up with alternative solutions?

**Comment by AArnott** [comment] 2019-03-23 17:29
I would recommend you stop synchronously blocking and use async throughout. If you can't do that, I would probably use Task.Wait() in an ASP.NET application. And if that deadlocks, then I would turn to JTF.

**Comment by gregpakes** [comment] 2019-03-23 18:38
Thanks - there are some areas where it’s pretty hard to write out the sync code, so I turned to JTF.

Thanks for the information and the help.

**Comment by gregpakes** [comment] 2019-03-29 04:55
@AArnott 

I just wanted to let you know what the blocker for us was with moving to 16.x as I have encountered it again.

We get the following exception when running AspNet_Merge.exe as a part of our deployment process:

```
C:\dev\vsts\isams\git\iSAMS\iSAMS_Website.metaproj : warning MSB3268: The primary reference "C:\dev\vsts\isams\git\iSAMS\packages\System.Threading.Tasks.E
xtensions.4.3.0\lib\portable-net45+win8+wp8+wpa81\System.Threading.Tasks.Extensions.dll" could not be resolved because it has an indirect dependency on the
framework assembly "System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targete
d framework. ".NETFramework,Version=v4.6". To resolve this problem, either remove the reference "C:\dev\vsts\isams\git\iSAMS\packages\System.Threading.Tasks
.Extensions.4.3.0\lib\portable-net45+win8+wp8+wpa81\System.Threading.Tasks.Extensions.dll" or retarget your application to a framework version which contain
s "System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
  C:\dev\vsts\isams\git\iSAMS\iSAMS_Website.metaproj : warning MSB3268: The primary reference "C:\dev\vsts\isams\git\iSAMS\packages\System.Threading.Tasks.E
xtensions.4.3.0\lib\portable-net45+win8+wp8+wpa81\System.Threading.Tasks.Extensions.dll" could not be resolved because it has an indirect dependency on the
framework assembly "System.Threading.Tasks, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently
 targeted framework. ".NETFramework,Version=v4.6". To resolve this problem, either remove the reference "C:\dev\vsts\isams\git\iSAMS\packages\System.Threadi
ng.Tasks.Extensions.4.3.0\lib\portable-net45+win8+wp8+wpa81\System.Threading.Tasks.Extensions.dll" or retarget your application to a framework version which
 contains "System.Threading.Tasks, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
  C:\dev\vsts\isams\git\iSAMS\iSAMS_Website.metaproj : warning MSB3268: The primary reference "C:\dev\vsts\isams\git\iSAMS\packages\System.Threading.Tasks.E
xtensions.4.3.0\lib\portable-net45+win8+wp8+wpa81\System.Threading.Tasks.Extensions.dll" could not be resolved because it has an indirect dependency on the
framework assembly "System.Collections, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently tar
geted framework. ".NETFramework,Version=v4.6". To resolve this problem, either remove the reference "C:\dev\vsts\isams\git\iSAMS\packages\System.Threading.T
asks.Extensions.4.3.0\lib\portable-net45+win8+wp8+wpa81\System.Threading.Tasks.Extensions.dll" or retarget your application to a framework version which con
tains "System.Collections, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
```

Our project is targeting .Net 4.6.
