### ISSUE TITLE
High lock contention in JTF

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vs-threading#135] opened 2017-06-10 12:28 UTC
During a profiling pass on a solution load of Roslyn.sln, I observed over 30 seconds of lock contention within this library.

The key offenders were the following:

| Method | Exclusive time in lock contention | Fix
| --- | --- | --- |
| JoinableTask.get_ApplicableJobSyncContext() | 7310ms | #409
| JoinableTask.Complete() | 5340ms |
| JoinableTaskContext.get_Factory() | 3587ms | #409
| JoinableTask.SetWrappedTask(Task) | 2505ms |
| JoinableTask.get_IsCompleted() | 2431ms |
| JoinableTaskCollection.Disjoin(JoinableTask) | 1727ms |
| JoinableTask.get_Task() | 1595ms | #411 
| JoinableTask.CompleteOnCurrentThread() | 1232ms |
| JoinableTaskCollection.Join() | 1155ms |

**Comment by AArnott** [comment] 2017-06-10 15:06
Is this a dupe of #132? JTF normally runs without much contention I think. But in #132 it's awful because a lock is held while performing an n^3 algorithm.

**Comment by sharwell** [comment] 2017-06-10 15:39
@AArnott I will try to determine if this is a duplicate. Keep in mind my test was run on a system with more cores than average (14C + HT), so based on what we know about end users today this information is more of a "this situation is inevitable but yet to get here".

**Comment by sharwell** [comment] 2017-06-10 15:45
@AArnott I see a total of 1863ms spent in `Disjoin`, so it's possible this is fallout from #132. I'm hesitant to treat it as a full duplicate since investigation suggests there are several cases above where lock-free fast paths are not unreasonable to incorporate.

**Comment by sharwell** [comment] 2018-11-08 12:34
I just collected a 30 second trace where 99.5% of the UI thread activity was vs-threading contention in three methods:

* JoinableTaskContext.get_Factory
* JoinableTask.get_ApplicableJobSyncContext
* JoinableTask.get_Task

With 28 logical processors, it was a fairly frequent occurrence to have problems with the global locking policy. However, a recent move to 64 is quickly making this unsustainable.

**Comment by AArnott** [comment] 2018-11-08 15:31
@sharwell Can you reproduce the problem, such that I could give you a patched vs-threading dll to see if it resolves the issue?

**Comment by sharwell** [comment] 2018-11-08 16:10
@AArnott I'm running a 2990WX with .NET 4.7.2. I can check to see if the issue is reproducible later this week.

**Closed** 2018-11-10 21:05 UTC
Labels: perf
