### ISSUE TITLE
Add Exception to VSTHRD100 when method in context is an event handler

### ISSUE THREAD

**Issue by sakshamsaxena** [microsoft/vs-threading#720] opened 2020-11-16 15:34 UTC
### Background
I have async callback, which I want to pass into System.Threading.Timer constructor. As of now, I have decided to use `private async void HandleTimerCallback(object state)` as the signature of the said callback function.

### Problem
However, this implementation is greeted with a `VSTHRD100` warning, which as you can see, would be impossible implement as TimerCallback will not accept it. I have to currently specifically ignore this single warning case by adding a suppression in the source code itself, but it seems a generic and practical problem that is worth solving for good.

### Proposed Solution
Stephen Cleary also clarified this in a [StackOverflow](https://stackoverflow.com/questions/38917818/pass-async-callback-to-timer-constructor#comment91001639_38918443)  comment. So I thought this is worth adding as an exception while assessing the rules.

**Comment by AArnott** [comment] 2020-11-16 16:53
Duplicate of #447

**Closed by AArnott** 2020-11-16 16:53 UTC
